# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlL-7mHf98fhznI5Ao5KnHNXpNKlTmaa
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics tensorflow -q
import os
import cv2
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt

from ultralytics import YOLO
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Automatically detect correct base path
root_path = "/content/drive/MyDrive/datasets/ua_detrac"

if os.path.exists(os.path.join(root_path, "DETRAC-Images", "DETRAC-Images")):
    base_path = os.path.join(root_path, "DETRAC-Images", "DETRAC-Images")
else:
    base_path = os.path.join(root_path, "DETRAC-Images")

print("Using base path:", base_path)
print("Sample folders:", os.listdir(base_path)[:3])

model = YOLO("yolov8n.pt")
vehicle_classes = [2, 3, 5, 7]  # car, motorcycle, bus, truck

all_counts = []
MAX_FRAMES_PER_FOLDER = 300   # limit for speed

for folder in sorted(os.listdir(base_path))[:40]:
    folder_path = os.path.join(base_path, folder)

    if os.path.isdir(folder_path):

        print("Processing:", folder)

        images = sorted(os.listdir(folder_path))[:MAX_FRAMES_PER_FOLDER]

        for img_name in images:
            img_path = os.path.join(folder_path, img_name)

            frame = cv2.imread(img_path)
            results = model(frame, verbose=False)

            count = sum(int(box.cls) in vehicle_classes for box in results[0].boxes)

            all_counts.append(count)

print("Total Frames Processed:", len(all_counts))

FRAMES_PER_MIN = 60

minute_counts = []

for i in range(0, len(all_counts), FRAMES_PER_MIN):
    chunk = all_counts[i:i+FRAMES_PER_MIN]
    if len(chunk) > 0:
        minute_counts.append(np.mean(chunk))

print("Total Minutes Generated:", len(minute_counts))

start_time = datetime.datetime(2024, 1, 1, 7, 30)

timestamps = [
    start_time + datetime.timedelta(minutes=i)
    for i in range(len(minute_counts))
]

df = pd.DataFrame({
    "timestamp": timestamps,
    "vehicle_count": minute_counts
})

df.head()

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df[["vehicle_count"]])

def create_dataset(data, time_step=10):
    X, y = [], []
    for i in range(len(data) - time_step):
        X.append(data[i:i+time_step])
        y.append(data[i+time_step])
    return np.array(X), np.array(y)

time_step = 10
X, y = create_dataset(scaled_data, time_step)

train_size = int(len(X) * 0.8)

X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

lstm_model = Sequential()
lstm_model.add(LSTM(50, input_shape=(time_step,1)))
lstm_model.add(Dense(1))

lstm_model.compile(optimizer="adam", loss="mse")
lstm_model.fit(X_train, y_train, epochs=20, batch_size=16, verbose=1)

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df[["vehicle_count"]])

def create_dataset(data, time_step=10):
    X, y = [], []
    for i in range(len(data) - time_step):
        X.append(data[i:i+time_step])
        y.append(data[i+time_step])
    return np.array(X), np.array(y)

time_step = 10
X, y = create_dataset(scaled_data, time_step)

train_size = int(len(X) * 0.8)

X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

lstm_model = Sequential()
lstm_model.add(LSTM(50, input_shape=(time_step,1)))
lstm_model.add(Dense(1))

lstm_model.compile(optimizer="adam", loss="mse")
lstm_model.fit(X_train, y_train, epochs=20, batch_size=16, verbose=1)

pred = lstm_model.predict(X_test)

pred = scaler.inverse_transform(pred)
y_test_actual = scaler.inverse_transform(y_test)

mae = mean_absolute_error(y_test_actual, pred)
rmse = np.sqrt(mean_squared_error(y_test_actual, pred))

epsilon = 1e-10
mape = np.mean(np.abs((y_test_actual - pred) / (y_test_actual + epsilon))) * 100
accuracy = 100 - mape

print("MAE:", round(mae,2))
print("RMSE:", round(rmse,2))
print("Prediction Accuracy:", round(accuracy,2), "%")

last_sequence = scaled_data[-time_step:]
current_input = last_sequence.reshape(1, time_step, 1)

future_predictions = []

for i in range(15):
    next_pred = lstm_model.predict(current_input, verbose=0)
    future_predictions.append(next_pred[0][0])
    current_input = np.concatenate(
        (current_input[:,1:,:], next_pred.reshape(1,1,1)),
        axis=1
    )
future_predictions = scaler.inverse_transform(
    np.array(future_predictions).reshape(-1,1)
)

future_predictions = np.round(future_predictions).astype(int)

def full_demo(image_path):

    global minute_counts, scaler, lstm_model, accuracy

    # ---- Step 1: Detect Vehicles ----
    results = model(image_path)
    count = sum(int(box.cls) in vehicle_classes for box in results[0].boxes)
    annotated = results[0].plot()

    # ---- Step 2: Create Temporary Updated Sequence ----
    temp_minute_counts = minute_counts.copy()

    # Replace last minute value with current count
    if len(temp_minute_counts) > 0:
        temp_minute_counts[-1] = count

    updated_df = pd.DataFrame({"vehicle_count": temp_minute_counts})
    scaled_data = scaler.transform(updated_df[["vehicle_count"]])

    time_step = 10

    if len(scaled_data) > time_step:

        last_sequence = scaled_data[-time_step:]
        current_input = last_sequence.reshape(1, time_step, 1)

        future_predictions = []

        for i in range(15):
            next_pred = lstm_model.predict(current_input, verbose=0)
            future_predictions.append(next_pred[0][0])

            current_input = np.concatenate(
                (current_input[:,1:,:], next_pred.reshape(1,1,1)),
                axis=1
            )

        future_predictions = scaler.inverse_transform(
            np.array(future_predictions).reshape(-1,1)
        )

        future_predictions = np.round(future_predictions).astype(int)

    else:
        future_predictions = ["Not enough data"]

    # ---- Step 3: Density ----
    max_capacity = max(minute_counts)
    density_percent = (count / max_capacity) * 100

    if density_percent < 40:
        density_label = "Low"
    elif density_percent < 75:
        density_label = "Medium"
    else:
        density_label = "High"

    # ---- Step 4: Display ----
    cv2.putText(annotated, f"Count: {count}", (20,40),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,0), 2)

    cv2.putText(annotated,
                f"Density: {density_label} ({density_percent:.1f}%)",
                (20,80),
                cv2.FONT_HERSHEY_SIMPLEX,
                1, (0,255,0), 2)

    plt.figure(figsize=(6,6))
    plt.imshow(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title("Real-Time Traffic Analysis")
    plt.show()

    print("Vehicle Count:", count)
    print("Traffic Density:", density_label)
    print("Prediction Accuracy:", round(accuracy,2), "%")

    print("\nNext 15 Minute Prediction:")
    print(np.array(future_predictions).flatten())

print(os.listdir(base_path))

folder_name = "MVI_20012"
print(os.listdir(os.path.join(base_path, folder_name))[:10])

test_image = os.path.join(base_path, "MVI_20012", "img00874.jpg")
full_demo(test_image)